CREATE (Anakin:person {gender:"male", home:"Tatooine"})
CREATE (Luke:person {gender:"male", home:"Tatooine"})
CREATE (Padmé:person {gender:"female"})
CREATE (R2D2:robot {home:"Naboo"})
CREATE (Padmé)-[:owns {episode:"I"}]->(R2D2)
CREATE (Anakin)-[:owns {episode:"II"}]->(R2D2)
CREATE (Anakin)-[:father {episode:"III"}]->(Luke)
CREATE (Padmé)-[:mother {episode:"III"}]->(Luke)
CREATE (R2D2)-[:owns {episode:"IV"}]->(Luke)
