// Generated by Peggy 3.0.2.
//
// https://peggyjs.org/

function peg$subclass(child, parent) {
  function C() {
    this.constructor = child 
  }
  C.prototype = parent.prototype
  child.prototype = new C()
}

function peg$SyntaxError(message, expected, found, location) {
  var self = Error.call(this, message)
  // istanbul ignore next Check is a necessary evil to support older environments
  if (Object.setPrototypeOf) {
    Object.setPrototypeOf(self, peg$SyntaxError.prototype)
  }
  self.expected = expected
  self.found = found
  self.location = location
  self.name = "SyntaxError"
  return self
}

peg$subclass(peg$SyntaxError, Error)

function peg$padEnd(str, targetLength, padString) {
  padString = padString || " "
  if (str.length > targetLength) {
    return str 
  }
  targetLength -= str.length
  padString += padString.repeat(targetLength)
  return str + padString.slice(0, targetLength)
}

peg$SyntaxError.prototype.format = function(sources) {
  var str = "Error: " + this.message
  if (this.location) {
    var src = null
    var k
    for (k = 0; k < sources.length; k++) {
      if (sources[k].source === this.location.source) {
        src = sources[k].text.split(/\r\n|\n|\r/g)
        break
      }
    }
    var s = this.location.start
    var offset_s = (this.location.source && (typeof this.location.source.offset === "function"))
      ? this.location.source.offset(s)
      : s
    var loc = this.location.source + ":" + offset_s.line + ":" + offset_s.column
    if (src) {
      var e = this.location.end
      var filler = peg$padEnd("", offset_s.line.toString().length, " ")
      var line = src[s.line - 1]
      var last = s.line === e.line ? e.column : line.length + 1
      var hatLen = (last - s.column) || 1
      str += "\n --> " + loc + "\n"
          + filler + " |\n"
          + offset_s.line + " | " + line + "\n"
          + filler + " | " + peg$padEnd("", s.column - 1, " ")
          + peg$padEnd("", hatLen, "^")
    } else {
      str += "\n at " + loc
    }
  }
  return str
}

peg$SyntaxError.buildMessage = function(expected, found) {
  var DESCRIBE_EXPECTATION_FNS = {
    literal: function(expectation) {
      return "\"" + literalEscape(expectation.text) + "\""
    },

    class: function(expectation) {
      var escapedParts = expectation.parts.map(function(part) {
        return Array.isArray(part)
          ? classEscape(part[0]) + "-" + classEscape(part[1])
          : classEscape(part)
      })

      return "[" + (expectation.inverted ? "^" : "") + escapedParts.join("") + "]"
    },

    any: function() {
      return "any character"
    },

    end: function() {
      return "end of input"
    },

    other: function(expectation) {
      return expectation.description
    },
  }

  function hex(ch) {
    return ch.charCodeAt(0).toString(16).toUpperCase()
  }

  function literalEscape(s) {
    return s
      .replace(/\\/g, "\\\\")
      .replace(/"/g,  "\\\"")
      .replace(/\0/g, "\\0")
      .replace(/\t/g, "\\t")
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/[\x00-\x0F]/g,          function(ch) {
        return "\\x0" + hex(ch) 
      })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) {
        return "\\x"  + hex(ch) 
      })
  }

  function classEscape(s) {
    return s
      .replace(/\\/g, "\\\\")
      .replace(/\]/g, "\\]")
      .replace(/\^/g, "\\^")
      .replace(/-/g,  "\\-")
      .replace(/\0/g, "\\0")
      .replace(/\t/g, "\\t")
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/[\x00-\x0F]/g,          function(ch) {
        return "\\x0" + hex(ch) 
      })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) {
        return "\\x"  + hex(ch) 
      })
  }

  function describeExpectation(expectation) {
    return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation)
  }

  function describeExpected(expected) {
    var descriptions = expected.map(describeExpectation)
    var i, j

    descriptions.sort()

    if (descriptions.length > 0) {
      for (i = 1, j = 1; i < descriptions.length; i++) {
        if (descriptions[i - 1] !== descriptions[i]) {
          descriptions[j] = descriptions[i]
          j++
        }
      }
      descriptions.length = j
    }

    switch (descriptions.length) {
      case 1:
        return descriptions[0]

      case 2:
        return descriptions[0] + " or " + descriptions[1]

      default:
        return descriptions.slice(0, -1).join(", ")
          + ", or "
          + descriptions[descriptions.length - 1]
    }
  }

  function describeFound(found) {
    return found ? "\"" + literalEscape(found) + "\"" : "end of input"
  }

  return "Expected " + describeExpected(expected) + " but " + describeFound(found) + " found."
}

function peg$parse(input, options) {
  options = options !== undefined ? options : {}

  var peg$FAILED = {}
  var peg$source = options.grammarSource

  var peg$startRuleFunctions = { NodeOrEdge: peg$parseNodeOrEdge }
  var peg$startRuleFunction = peg$parseNodeOrEdge

  var peg$c0 = ":"
  var peg$c1 = "--"
  var peg$c2 = "->"
  var peg$c3 = "-"
  var peg$c4 = "."
  var peg$c5 = "0"
  var peg$c6 = "+"
  var peg$c7 = "'"
  var peg$c8 = "\""
  var peg$c9 = "\\"
  var peg$c10 = "b"
  var peg$c11 = "f"
  var peg$c12 = "n"
  var peg$c13 = "r"
  var peg$c14 = "t"
  var peg$c15 = "v"

  var peg$r0 = /^[0-9]/
  var peg$r1 = /^[1-9]/
  var peg$r2 = /^[eE]/
  var peg$r3 = /^[ \t]/
  var peg$r4 = /^[: \t\r\n]/
  var peg$r5 = /^[^: \t\r\n]/
  var peg$r6 = /^[\r\n]/
  var peg$r7 = /^[^\r\n]/

  var peg$e0 = peg$literalExpectation(":", false)
  var peg$e1 = peg$literalExpectation("--", false)
  var peg$e2 = peg$literalExpectation("->", false)
  var peg$e3 = peg$literalExpectation("-", false)
  var peg$e4 = peg$literalExpectation(".", false)
  var peg$e5 = peg$classExpectation([["0", "9"]], false, false)
  var peg$e6 = peg$literalExpectation("0", false)
  var peg$e7 = peg$classExpectation([["1", "9"]], false, false)
  var peg$e8 = peg$classExpectation(["e", "E"], false, false)
  var peg$e9 = peg$literalExpectation("+", false)
  var peg$e10 = peg$literalExpectation("'", false)
  var peg$e11 = peg$literalExpectation("\"", false)
  var peg$e12 = peg$literalExpectation("\\", false)
  var peg$e13 = peg$literalExpectation("b", false)
  var peg$e14 = peg$literalExpectation("f", false)
  var peg$e15 = peg$literalExpectation("n", false)
  var peg$e16 = peg$literalExpectation("r", false)
  var peg$e17 = peg$literalExpectation("t", false)
  var peg$e18 = peg$literalExpectation("v", false)
  var peg$e19 = peg$anyExpectation()
  var peg$e20 = peg$classExpectation([" ", "\t"], false, false)
  var peg$e21 = peg$classExpectation([":", " ", "\t", "\r", "\n"], false, false)
  var peg$e22 = peg$classExpectation([":", " ", "\t", "\r", "\n"], true, false)
  var peg$e23 = peg$classExpectation(["\r", "\n"], false, false)
  var peg$e24 = peg$classExpectation(["\r", "\n"], true, false)

  var peg$f0 = function(lines) {
    return {
      nodes: lines.map(l => l.node).filter(v => v),
      edges: lines.map(l => l.edge).filter(v => v),
      nodeCount: nodeCount,
      edgeCount: edgeCount,
      nodeLabels: nodeLabelHash,
      edgeLabels: edgeLabelHash,
      nodeProperties: nodePropHash,
      edgeProperties: edgePropHash,
    }
  }
  var peg$f1 = function(n) {
    return {
      node: n,
    }
  }
  var peg$f2 = function(e) {
    return {
      edge: e,
    }
  }
  var peg$f3 = function(id, l, p) {
    let propObj = {}
    p.forEach(prop => {
      if (propObj[prop.key]) {
        propObj[prop.key].push(prop.value)
      } else {
        propObj[prop.key] = [prop.value]
      }
      // nodePropHash[prop.key] = true;
      if (nodePropHash[prop.key]) {
        nodePropHash[prop.key]++
      } else {
        nodePropHash[prop.key] = 1
      }
    })

    nodeCount++

    l.forEach(label => {
      if (nodeLabelHash[label]) {
        nodeLabelHash[label]++
      } else {
        nodeLabelHash[label] = 1
      }
    })

    return {
      id: id,
      labels: l,
      properties: propObj,
    }
  }
  var peg$f4 = function(f, d, t, l, p) {
    let propObj = {}
    p.forEach(prop => {
      if (propObj[prop.key]) {
        propObj[prop.key].push(prop.value)
      } else {
        propObj[prop.key] = [prop.value]
      }
      // edgePropHash[prop.key] = true;
      if (edgePropHash[prop.key]) {
        edgePropHash[prop.key]++
      } else {
        edgePropHash[prop.key] = 1
      }
    })

    edgeCount++

    l.forEach(label => {
      if (edgeLabelHash[label]) {
        edgeLabelHash[label]++
      } else {
        edgeLabelHash[label] = 1
      }
    })

    return {
      from: f,
      to: t,
      direction: d,
      labels: l,
      properties: propObj,
    }
  }
  var peg$f5 = function(l) {
    return l
  }
  var peg$f6 = function(k, v) {
    return {
      key: k,
      value: v,
    }
  }
  var peg$f7 = function() {
    return "\b"
  }
  var peg$f8 = function() {
    return "\f"
  }
  var peg$f9 = function() {
    return "\n"
  }
  var peg$f10 = function() {
    return "\r"
  }
  var peg$f11 = function() {
    return "\t"
  }
  var peg$f12 = function() {
    return "\x0B"
  }
  var peg$f13 = function(char) {
    return char
  }
  var peg$f14 = function(esc) {
    return esc
  }
  var peg$f15 = function(char) {
    return char
  }
  var peg$f16 = function(esc) {
    return esc
  }
  var peg$f17 = function() {
    return text()
  }
  var peg$f18 = function(chars) {
    return chars.join("")
  }
  var peg$f19 = function(chars) { 
    return chars.join("")
  }
  var peg$f20 = function(chars) {
    return chars.join("")
  }
  var peg$currPos = 0
  var peg$savedPos = 0
  var peg$posDetailsCache = [{ line: 1, column: 1 }]
  var peg$maxFailPos = 0
  var peg$maxFailExpected = []
  var peg$silentFails = 0

  var peg$result

  if ("startRule" in options) {
    if (!(options.startRule in peg$startRuleFunctions)) {
      throw new Error("Can't start parsing from rule \"" + options.startRule + "\".")
    }

    peg$startRuleFunction = peg$startRuleFunctions[options.startRule]
  }

  function text() {
    return input.substring(peg$savedPos, peg$currPos)
  }

  function offset() {
    return peg$savedPos
  }

  function range() {
    return {
      source: peg$source,
      start: peg$savedPos,
      end: peg$currPos,
    }
  }

  function location() {
    return peg$computeLocation(peg$savedPos, peg$currPos)
  }

  function expected(description, location) {
    location = location !== undefined
      ? location
      : peg$computeLocation(peg$savedPos, peg$currPos)

    throw peg$buildStructuredError(
      [peg$otherExpectation(description)],
      input.substring(peg$savedPos, peg$currPos),
      location,
    )
  }

  function error(message, location) {
    location = location !== undefined
      ? location
      : peg$computeLocation(peg$savedPos, peg$currPos)

    throw peg$buildSimpleError(message, location)
  }

  function peg$literalExpectation(text, ignoreCase) {
    return { type: "literal", text: text, ignoreCase: ignoreCase }
  }

  function peg$classExpectation(parts, inverted, ignoreCase) {
    return { type: "class", parts: parts, inverted: inverted, ignoreCase: ignoreCase }
  }

  function peg$anyExpectation() {
    return { type: "any" }
  }

  function peg$endExpectation() {
    return { type: "end" }
  }

  function peg$otherExpectation(description) {
    return { type: "other", description: description }
  }

  function peg$computePosDetails(pos) {
    var details = peg$posDetailsCache[pos]
    var p

    if (details) {
      return details
    } else {
      p = pos - 1
      while (!peg$posDetailsCache[p]) {
        p--
      }

      details = peg$posDetailsCache[p]
      details = {
        line: details.line,
        column: details.column,
      }

      while (p < pos) {
        if (input.charCodeAt(p) === 10) {
          details.line++
          details.column = 1
        } else {
          details.column++
        }

        p++
      }

      peg$posDetailsCache[pos] = details

      return details
    }
  }

  function peg$computeLocation(startPos, endPos, offset) {
    var startPosDetails = peg$computePosDetails(startPos)
    var endPosDetails = peg$computePosDetails(endPos)

    var res = {
      source: peg$source,
      start: {
        offset: startPos,
        line: startPosDetails.line,
        column: startPosDetails.column,
      },
      end: {
        offset: endPos,
        line: endPosDetails.line,
        column: endPosDetails.column,
      },
    }
    if (offset && peg$source && (typeof peg$source.offset === "function")) {
      res.start = peg$source.offset(res.start)
      res.end = peg$source.offset(res.end)
    }
    return res
  }

  function peg$fail(expected) {
    if (peg$currPos < peg$maxFailPos) {
      return 
    }

    if (peg$currPos > peg$maxFailPos) {
      peg$maxFailPos = peg$currPos
      peg$maxFailExpected = []
    }

    peg$maxFailExpected.push(expected)
  }

  function peg$buildSimpleError(message, location) {
    return new peg$SyntaxError(message, null, null, location)
  }

  function peg$buildStructuredError(expected, found, location) {
    return new peg$SyntaxError(
      peg$SyntaxError.buildMessage(expected, found),
      expected,
      found,
      location,
    )
  }

  function peg$parsePG() {
    var s0, s1, s2

    s0 = peg$parseEOF()
    if (s0 === peg$FAILED) {
      s0 = peg$currPos
      s1 = []
      s2 = peg$parseNodeOrEdge()
      if (s2 !== peg$FAILED) {
        while (s2 !== peg$FAILED) {
          s1.push(s2)
          s2 = peg$parseNodeOrEdge()
        }
      } else {
        s1 = peg$FAILED
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseEOF()
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0
          s0 = peg$f0(s1)
        } else {
          peg$currPos = s0
          s0 = peg$FAILED
        }
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    }

    return s0
  }

  function peg$parseNodeOrEdge() {
    var s0, s1

    s0 = peg$currPos
    s1 = peg$parseNode()
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0
      s1 = peg$f1(s1)
    }
    s0 = s1
    if (s0 === peg$FAILED) {
      s0 = peg$currPos
      s1 = peg$parseEdge()
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0
        s1 = peg$f2(s1)
      }
      s0 = s1
      if (s0 === peg$FAILED) {
        s0 = peg$parseEmptyLine()
      }
    }

    return s0
  }

  function peg$parseNode() {
    var s0, s1, s2, s3, s4, s5

    s0 = peg$currPos
    s1 = peg$currPos
    s2 = peg$parseValue()
    if (s2 !== peg$FAILED) {
      s1 = input.substring(s1, peg$currPos)
    } else {
      s1 = s2
    }
    if (s1 !== peg$FAILED) {
      s2 = []
      s3 = peg$parseLabel()
      while (s3 !== peg$FAILED) {
        s2.push(s3)
        s3 = peg$parseLabel()
      }
      s3 = []
      s4 = peg$parseProperty()
      while (s4 !== peg$FAILED) {
        s3.push(s4)
        s4 = peg$parseProperty()
      }
      s4 = []
      s5 = peg$parseWS()
      while (s5 !== peg$FAILED) {
        s4.push(s5)
        s5 = peg$parseWS()
      }
      s5 = peg$parseEndOfLine()
      if (s5 !== peg$FAILED) {
        peg$savedPos = s0
        s0 = peg$f3(s1, s2, s3)
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }

    return s0
  }

  function peg$parseEdge() {
    var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9

    s0 = peg$currPos
    s1 = peg$currPos
    s2 = peg$parseValue()
    if (s2 !== peg$FAILED) {
      s1 = input.substring(s1, peg$currPos)
    } else {
      s1 = s2
    }
    if (s1 !== peg$FAILED) {
      s2 = []
      s3 = peg$parseWS()
      if (s3 !== peg$FAILED) {
        while (s3 !== peg$FAILED) {
          s2.push(s3)
          s3 = peg$parseWS()
        }
      } else {
        s2 = peg$FAILED
      }
      if (s2 !== peg$FAILED) {
        s3 = peg$parseDirection()
        if (s3 !== peg$FAILED) {
          s4 = []
          s5 = peg$parseWS()
          if (s5 !== peg$FAILED) {
            while (s5 !== peg$FAILED) {
              s4.push(s5)
              s5 = peg$parseWS()
            }
          } else {
            s4 = peg$FAILED
          }
          if (s4 !== peg$FAILED) {
            s5 = peg$parseValue()
            if (s5 !== peg$FAILED) {
              s6 = []
              s7 = peg$parseLabel()
              while (s7 !== peg$FAILED) {
                s6.push(s7)
                s7 = peg$parseLabel()
              }
              s7 = []
              s8 = peg$parseProperty()
              while (s8 !== peg$FAILED) {
                s7.push(s8)
                s8 = peg$parseProperty()
              }
              s8 = []
              s9 = peg$parseWS()
              while (s9 !== peg$FAILED) {
                s8.push(s9)
                s9 = peg$parseWS()
              }
              s9 = peg$parseEndOfLine()
              if (s9 !== peg$FAILED) {
                peg$savedPos = s0
                s0 = peg$f4(s1, s3, s5, s6, s7)
              } else {
                peg$currPos = s0
                s0 = peg$FAILED
              }
            } else {
              peg$currPos = s0
              s0 = peg$FAILED
            }
          } else {
            peg$currPos = s0
            s0 = peg$FAILED
          }
        } else {
          peg$currPos = s0
          s0 = peg$FAILED
        }
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }

    return s0
  }

  function peg$parseLabel() {
    var s0, s1, s2, s3, s4

    s0 = peg$currPos
    s1 = []
    s2 = peg$parseDelimiter()
    if (s2 !== peg$FAILED) {
      while (s2 !== peg$FAILED) {
        s1.push(s2)
        s2 = peg$parseDelimiter()
      }
    } else {
      s1 = peg$FAILED
    }
    if (s1 !== peg$FAILED) {
      if (input.charCodeAt(peg$currPos) === 58) {
        s2 = peg$c0
        peg$currPos++
      } else {
        s2 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e0) 
        }
      }
      if (s2 !== peg$FAILED) {
        s3 = []
        s4 = peg$parseWS()
        while (s4 !== peg$FAILED) {
          s3.push(s4)
          s4 = peg$parseWS()
        }
        s4 = peg$parseValue()
        if (s4 !== peg$FAILED) {
          peg$savedPos = s0
          s0 = peg$f5(s4)
        } else {
          peg$currPos = s0
          s0 = peg$FAILED
        }
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }

    return s0
  }

  function peg$parseProperty() {
    var s0, s1, s2, s3, s4, s5, s6

    s0 = peg$currPos
    s1 = []
    s2 = peg$parseDelimiter()
    if (s2 !== peg$FAILED) {
      while (s2 !== peg$FAILED) {
        s1.push(s2)
        s2 = peg$parseDelimiter()
      }
    } else {
      s1 = peg$FAILED
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseValue()
      if (s2 !== peg$FAILED) {
        s3 = []
        s4 = peg$parseWS()
        while (s4 !== peg$FAILED) {
          s3.push(s4)
          s4 = peg$parseWS()
        }
        if (input.charCodeAt(peg$currPos) === 58) {
          s4 = peg$c0
          peg$currPos++
        } else {
          s4 = peg$FAILED
          if (peg$silentFails === 0) {
            peg$fail(peg$e0) 
          }
        }
        if (s4 !== peg$FAILED) {
          s5 = []
          s6 = peg$parseWS()
          while (s6 !== peg$FAILED) {
            s5.push(s6)
            s6 = peg$parseWS()
          }
          s6 = peg$parseValue()
          if (s6 !== peg$FAILED) {
            peg$savedPos = s0
            s0 = peg$f6(s2, s6)
          } else {
            peg$currPos = s0
            s0 = peg$FAILED
          }
        } else {
          peg$currPos = s0
          s0 = peg$FAILED
        }
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }

    return s0
  }

  function peg$parseDirection() {
    var s0

    if (input.substr(peg$currPos, 2) === peg$c1) {
      s0 = peg$c1
      peg$currPos += 2
    } else {
      s0 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e1) 
      }
    }
    if (s0 === peg$FAILED) {
      if (input.substr(peg$currPos, 2) === peg$c2) {
        s0 = peg$c2
        peg$currPos += 2
      } else {
        s0 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e2) 
        }
      }
    }

    return s0
  }

  function peg$parseNumber() {
    var s0, s1, s2, s3, s4, s5, s6

    s0 = peg$currPos
    if (input.charCodeAt(peg$currPos) === 45) {
      s1 = peg$c3
      peg$currPos++
    } else {
      s1 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e3) 
      }
    }
    if (s1 === peg$FAILED) {
      s1 = null
    }
    s2 = peg$parseInteger()
    if (s2 !== peg$FAILED) {
      s3 = peg$currPos
      if (input.charCodeAt(peg$currPos) === 46) {
        s4 = peg$c4
        peg$currPos++
      } else {
        s4 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e4) 
        }
      }
      if (s4 !== peg$FAILED) {
        s5 = []
        if (peg$r0.test(input.charAt(peg$currPos))) {
          s6 = input.charAt(peg$currPos)
          peg$currPos++
        } else {
          s6 = peg$FAILED
          if (peg$silentFails === 0) {
            peg$fail(peg$e5) 
          }
        }
        if (s6 !== peg$FAILED) {
          while (s6 !== peg$FAILED) {
            s5.push(s6)
            if (peg$r0.test(input.charAt(peg$currPos))) {
              s6 = input.charAt(peg$currPos)
              peg$currPos++
            } else {
              s6 = peg$FAILED
              if (peg$silentFails === 0) {
                peg$fail(peg$e5) 
              }
            }
          }
        } else {
          s5 = peg$FAILED
        }
        if (s5 !== peg$FAILED) {
          s4 = [s4, s5]
          s3 = s4
        } else {
          peg$currPos = s3
          s3 = peg$FAILED
        }
      } else {
        peg$currPos = s3
        s3 = peg$FAILED
      }
      if (s3 === peg$FAILED) {
        s3 = null
      }
      s4 = peg$parseExp()
      if (s4 === peg$FAILED) {
        s4 = null
      }
      s1 = [s1, s2, s3, s4]
      s0 = s1
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }

    return s0
  }

  function peg$parseInteger() {
    var s0, s1, s2, s3

    if (input.charCodeAt(peg$currPos) === 48) {
      s0 = peg$c5
      peg$currPos++
    } else {
      s0 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e6) 
      }
    }
    if (s0 === peg$FAILED) {
      s0 = peg$currPos
      if (peg$r1.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos)
        peg$currPos++
      } else {
        s1 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e7) 
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = []
        if (peg$r0.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos)
          peg$currPos++
        } else {
          s3 = peg$FAILED
          if (peg$silentFails === 0) {
            peg$fail(peg$e5) 
          }
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3)
          if (peg$r0.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos)
            peg$currPos++
          } else {
            s3 = peg$FAILED
            if (peg$silentFails === 0) {
              peg$fail(peg$e5) 
            }
          }
        }
        s1 = [s1, s2]
        s0 = s1
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    }

    return s0
  }

  function peg$parseExp() {
    var s0, s1, s2, s3, s4

    s0 = peg$currPos
    if (peg$r2.test(input.charAt(peg$currPos))) {
      s1 = input.charAt(peg$currPos)
      peg$currPos++
    } else {
      s1 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e8) 
      }
    }
    if (s1 !== peg$FAILED) {
      if (input.charCodeAt(peg$currPos) === 45) {
        s2 = peg$c3
        peg$currPos++
      } else {
        s2 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e3) 
        }
      }
      if (s2 === peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 43) {
          s2 = peg$c6
          peg$currPos++
        } else {
          s2 = peg$FAILED
          if (peg$silentFails === 0) {
            peg$fail(peg$e9) 
          }
        }
      }
      if (s2 === peg$FAILED) {
        s2 = null
      }
      s3 = []
      if (peg$r0.test(input.charAt(peg$currPos))) {
        s4 = input.charAt(peg$currPos)
        peg$currPos++
      } else {
        s4 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e5) 
        }
      }
      if (s4 !== peg$FAILED) {
        while (s4 !== peg$FAILED) {
          s3.push(s4)
          if (peg$r0.test(input.charAt(peg$currPos))) {
            s4 = input.charAt(peg$currPos)
            peg$currPos++
          } else {
            s4 = peg$FAILED
            if (peg$silentFails === 0) {
              peg$fail(peg$e5) 
            }
          }
        }
      } else {
        s3 = peg$FAILED
      }
      if (s3 !== peg$FAILED) {
        s1 = [s1, s2, s3]
        s0 = s1
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }

    return s0
  }

  function peg$parseEscapedChar() {
    var s0, s1

    if (input.charCodeAt(peg$currPos) === 39) {
      s0 = peg$c7
      peg$currPos++
    } else {
      s0 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e10) 
      }
    }
    if (s0 === peg$FAILED) {
      if (input.charCodeAt(peg$currPos) === 34) {
        s0 = peg$c8
        peg$currPos++
      } else {
        s0 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e11) 
        }
      }
      if (s0 === peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 92) {
          s0 = peg$c9
          peg$currPos++
        } else {
          s0 = peg$FAILED
          if (peg$silentFails === 0) {
            peg$fail(peg$e12) 
          }
        }
        if (s0 === peg$FAILED) {
          s0 = peg$currPos
          if (input.charCodeAt(peg$currPos) === 98) {
            s1 = peg$c10
            peg$currPos++
          } else {
            s1 = peg$FAILED
            if (peg$silentFails === 0) {
              peg$fail(peg$e13) 
            }
          }
          if (s1 !== peg$FAILED) {
            peg$savedPos = s0
            s1 = peg$f7()
          }
          s0 = s1
          if (s0 === peg$FAILED) {
            s0 = peg$currPos
            if (input.charCodeAt(peg$currPos) === 102) {
              s1 = peg$c11
              peg$currPos++
            } else {
              s1 = peg$FAILED
              if (peg$silentFails === 0) {
                peg$fail(peg$e14) 
              }
            }
            if (s1 !== peg$FAILED) {
              peg$savedPos = s0
              s1 = peg$f8()
            }
            s0 = s1
            if (s0 === peg$FAILED) {
              s0 = peg$currPos
              if (input.charCodeAt(peg$currPos) === 110) {
                s1 = peg$c12
                peg$currPos++
              } else {
                s1 = peg$FAILED
                if (peg$silentFails === 0) {
                  peg$fail(peg$e15) 
                }
              }
              if (s1 !== peg$FAILED) {
                peg$savedPos = s0
                s1 = peg$f9()
              }
              s0 = s1
              if (s0 === peg$FAILED) {
                s0 = peg$currPos
                if (input.charCodeAt(peg$currPos) === 114) {
                  s1 = peg$c13
                  peg$currPos++
                } else {
                  s1 = peg$FAILED
                  if (peg$silentFails === 0) {
                    peg$fail(peg$e16) 
                  }
                }
                if (s1 !== peg$FAILED) {
                  peg$savedPos = s0
                  s1 = peg$f10()
                }
                s0 = s1
                if (s0 === peg$FAILED) {
                  s0 = peg$currPos
                  if (input.charCodeAt(peg$currPos) === 116) {
                    s1 = peg$c14
                    peg$currPos++
                  } else {
                    s1 = peg$FAILED
                    if (peg$silentFails === 0) {
                      peg$fail(peg$e17) 
                    }
                  }
                  if (s1 !== peg$FAILED) {
                    peg$savedPos = s0
                    s1 = peg$f11()
                  }
                  s0 = s1
                  if (s0 === peg$FAILED) {
                    s0 = peg$currPos
                    if (input.charCodeAt(peg$currPos) === 118) {
                      s1 = peg$c15
                      peg$currPos++
                    } else {
                      s1 = peg$FAILED
                      if (peg$silentFails === 0) {
                        peg$fail(peg$e18) 
                      }
                    }
                    if (s1 !== peg$FAILED) {
                      peg$savedPos = s0
                      s1 = peg$f12()
                    }
                    s0 = s1
                  }
                }
              }
            }
          }
        }
      }
    }

    return s0
  }

  function peg$parseDoubleQuotedChar() {
    var s0, s1, s2

    s0 = peg$currPos
    s1 = peg$currPos
    peg$silentFails++
    if (input.charCodeAt(peg$currPos) === 34) {
      s2 = peg$c8
      peg$currPos++
    } else {
      s2 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e11) 
      }
    }
    if (s2 === peg$FAILED) {
      if (input.charCodeAt(peg$currPos) === 92) {
        s2 = peg$c9
        peg$currPos++
      } else {
        s2 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e12) 
        }
      }
    }
    peg$silentFails--
    if (s2 === peg$FAILED) {
      s1 = undefined
    } else {
      peg$currPos = s1
      s1 = peg$FAILED
    }
    if (s1 !== peg$FAILED) {
      if (input.length > peg$currPos) {
        s2 = input.charAt(peg$currPos)
        peg$currPos++
      } else {
        s2 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e19) 
        }
      }
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0
        s0 = peg$f13(s2)
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }
    if (s0 === peg$FAILED) {
      s0 = peg$currPos
      if (input.charCodeAt(peg$currPos) === 92) {
        s1 = peg$c9
        peg$currPos++
      } else {
        s1 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e12) 
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseEscapedChar()
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0
          s0 = peg$f14(s2)
        } else {
          peg$currPos = s0
          s0 = peg$FAILED
        }
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    }

    return s0
  }

  function peg$parseSingleQuotedChar() {
    var s0, s1, s2

    s0 = peg$currPos
    s1 = peg$currPos
    peg$silentFails++
    if (input.charCodeAt(peg$currPos) === 39) {
      s2 = peg$c7
      peg$currPos++
    } else {
      s2 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e10) 
      }
    }
    if (s2 === peg$FAILED) {
      if (input.charCodeAt(peg$currPos) === 92) {
        s2 = peg$c9
        peg$currPos++
      } else {
        s2 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e12) 
        }
      }
    }
    peg$silentFails--
    if (s2 === peg$FAILED) {
      s1 = undefined
    } else {
      peg$currPos = s1
      s1 = peg$FAILED
    }
    if (s1 !== peg$FAILED) {
      if (input.length > peg$currPos) {
        s2 = input.charAt(peg$currPos)
        peg$currPos++
      } else {
        s2 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e19) 
        }
      }
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0
        s0 = peg$f15(s2)
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }
    if (s0 === peg$FAILED) {
      s0 = peg$currPos
      if (input.charCodeAt(peg$currPos) === 92) {
        s1 = peg$c9
        peg$currPos++
      } else {
        s1 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e12) 
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseEscapedChar()
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0
          s0 = peg$f16(s2)
        } else {
          peg$currPos = s0
          s0 = peg$FAILED
        }
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    }

    return s0
  }

  function peg$parseValue() {
    var s0, s1, s2, s3

    s0 = peg$currPos
    s1 = peg$parseNumber()
    if (s1 !== peg$FAILED) {
      s2 = peg$currPos
      peg$silentFails++
      s3 = peg$parseSPECIAL_CHAR()
      peg$silentFails--
      if (s3 !== peg$FAILED) {
        peg$currPos = s2
        s2 = undefined
      } else {
        s2 = peg$FAILED
      }
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0
        s0 = peg$f17()
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }
    if (s0 === peg$FAILED) {
      s0 = peg$currPos
      if (input.charCodeAt(peg$currPos) === 34) {
        s1 = peg$c8
        peg$currPos++
      } else {
        s1 = peg$FAILED
        if (peg$silentFails === 0) {
          peg$fail(peg$e11) 
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = []
        s3 = peg$parseDoubleQuotedChar()
        while (s3 !== peg$FAILED) {
          s2.push(s3)
          s3 = peg$parseDoubleQuotedChar()
        }
        if (input.charCodeAt(peg$currPos) === 34) {
          s3 = peg$c8
          peg$currPos++
        } else {
          s3 = peg$FAILED
          if (peg$silentFails === 0) {
            peg$fail(peg$e11) 
          }
        }
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0
          s0 = peg$f18(s2)
        } else {
          peg$currPos = s0
          s0 = peg$FAILED
        }
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos
        if (input.charCodeAt(peg$currPos) === 39) {
          s1 = peg$c7
          peg$currPos++
        } else {
          s1 = peg$FAILED
          if (peg$silentFails === 0) {
            peg$fail(peg$e10) 
          }
        }
        if (s1 !== peg$FAILED) {
          s2 = []
          s3 = peg$parseSingleQuotedChar()
          while (s3 !== peg$FAILED) {
            s2.push(s3)
            s3 = peg$parseSingleQuotedChar()
          }
          if (input.charCodeAt(peg$currPos) === 39) {
            s3 = peg$c7
            peg$currPos++
          } else {
            s3 = peg$FAILED
            if (peg$silentFails === 0) {
              peg$fail(peg$e10) 
            }
          }
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0
            s0 = peg$f19(s2)
          } else {
            peg$currPos = s0
            s0 = peg$FAILED
          }
        } else {
          peg$currPos = s0
          s0 = peg$FAILED
        }
        if (s0 === peg$FAILED) {
          s0 = peg$currPos
          s1 = []
          s2 = peg$parseNON_SPECIAL_CHAR()
          if (s2 !== peg$FAILED) {
            while (s2 !== peg$FAILED) {
              s1.push(s2)
              s2 = peg$parseNON_SPECIAL_CHAR()
            }
          } else {
            s1 = peg$FAILED
          }
          if (s1 !== peg$FAILED) {
            peg$savedPos = s0
            s1 = peg$f20(s1)
          }
          s0 = s1
        }
      }
    }

    return s0
  }

  function peg$parseWS() {
    var s0

    if (peg$r3.test(input.charAt(peg$currPos))) {
      s0 = input.charAt(peg$currPos)
      peg$currPos++
    } else {
      s0 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e20) 
      }
    }

    return s0
  }

  function peg$parseSPECIAL_CHAR() {
    var s0

    if (peg$r4.test(input.charAt(peg$currPos))) {
      s0 = input.charAt(peg$currPos)
      peg$currPos++
    } else {
      s0 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e21) 
      }
    }

    return s0
  }

  function peg$parseNON_SPECIAL_CHAR() {
    var s0

    if (peg$r5.test(input.charAt(peg$currPos))) {
      s0 = input.charAt(peg$currPos)
      peg$currPos++
    } else {
      s0 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e22) 
      }
    }

    return s0
  }

  function peg$parseNEWLINE() {
    var s0

    if (peg$r6.test(input.charAt(peg$currPos))) {
      s0 = input.charAt(peg$currPos)
      peg$currPos++
    } else {
      s0 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e23) 
      }
    }

    return s0
  }

  function peg$parseNON_NEWLINE() {
    var s0

    if (peg$r7.test(input.charAt(peg$currPos))) {
      s0 = input.charAt(peg$currPos)
      peg$currPos++
    } else {
      s0 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e24) 
      }
    }

    return s0
  }

  function peg$parseEOF() {
    var s0, s1

    s0 = peg$currPos
    peg$silentFails++
    if (input.length > peg$currPos) {
      s1 = input.charAt(peg$currPos)
      peg$currPos++
    } else {
      s1 = peg$FAILED
      if (peg$silentFails === 0) {
        peg$fail(peg$e19) 
      }
    }
    peg$silentFails--
    if (s1 === peg$FAILED) {
      s0 = undefined
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }

    return s0
  }

  function peg$parseEndOfLine() {
    var s0

    s0 = peg$parseEOF()
    if (s0 === peg$FAILED) {
      s0 = peg$parseNEWLINE()
    }

    return s0
  }

  function peg$parseDelimiter() {
    var s0, s1, s2, s3, s4

    s0 = peg$currPos
    s1 = []
    s2 = peg$parseWS()
    while (s2 !== peg$FAILED) {
      s1.push(s2)
      s2 = peg$parseWS()
    }
    s2 = peg$parseNEWLINE()
    if (s2 !== peg$FAILED) {
      s3 = []
      s4 = peg$parseWS()
      if (s4 !== peg$FAILED) {
        while (s4 !== peg$FAILED) {
          s3.push(s4)
          s4 = peg$parseWS()
        }
      } else {
        s3 = peg$FAILED
      }
      if (s3 !== peg$FAILED) {
        s1 = [s1, s2, s3]
        s0 = s1
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }
    if (s0 === peg$FAILED) {
      s0 = []
      s1 = peg$parseWS()
      if (s1 !== peg$FAILED) {
        while (s1 !== peg$FAILED) {
          s0.push(s1)
          s1 = peg$parseWS()
        }
      } else {
        s0 = peg$FAILED
      }
    }

    return s0
  }

  function peg$parseEmptyLine() {
    var s0, s1, s2

    s0 = peg$currPos
    s1 = []
    s2 = peg$parseWS()
    if (s2 !== peg$FAILED) {
      while (s2 !== peg$FAILED) {
        s1.push(s2)
        s2 = peg$parseWS()
      }
    } else {
      s1 = peg$FAILED
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseEOF()
      if (s2 !== peg$FAILED) {
        s1 = [s1, s2]
        s0 = s1
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    } else {
      peg$currPos = s0
      s0 = peg$FAILED
    }
    if (s0 === peg$FAILED) {
      s0 = peg$currPos
      s1 = []
      s2 = peg$parseWS()
      while (s2 !== peg$FAILED) {
        s1.push(s2)
        s2 = peg$parseWS()
      }
      s2 = peg$parseNEWLINE()
      if (s2 !== peg$FAILED) {
        s1 = [s1, s2]
        s0 = s1
      } else {
        peg$currPos = s0
        s0 = peg$FAILED
      }
    }

    return s0
  }


  let nodeCount = 0
  let edgeCount = 0
  let nodeLabelHash = {}
  let edgeLabelHash = {}
  let nodePropHash = {}
  let edgePropHash = {}

  peg$result = peg$startRuleFunction()

  if (peg$result !== peg$FAILED && peg$currPos === input.length) {
    return peg$result
  } else {
    if (peg$result !== peg$FAILED && peg$currPos < input.length) {
      peg$fail(peg$endExpectation())
    }

    throw peg$buildStructuredError(
      peg$maxFailExpected,
      peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null,
      peg$maxFailPos < input.length
        ? peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1)
        : peg$computeLocation(peg$maxFailPos, peg$maxFailPos),
    )
  }
}

export {
  peg$SyntaxError as SyntaxError,

  peg$parse as parse,
}
